// AUTO-GENERATED a partir do ficheiro oficial DPA (21 províncias, 326 municípios, 542 comunas).
// Reforma administrativa de Angola, 2024. Fonte única para selects dependentes.
import { PROVINCIAS_ANGOLA, type ProvinciaAngola } from "./provincias";

export type { ProvinciaAngola };

export const DPA_ANGOLA: Record<ProvinciaAngola, Record<string, string[]>> = {
  "Bengo": {
    "Ambriz": ["Ambriz", "Bela Vista", "Tabi"],
    "Barra do Dande": ["N_A"],
    "Bula Atumba": ["Bula Atumba", "Quiage"],
    "Dande": ["Caxito", "Mabubas", "Quicabo"],
    "Dange Quitexe": ["Aldeia Viçosa", "Quitexe"],
    "Muxaluando": ["Cage Mazumbo", "Muxaluando", "Quixico"],
    "Nambuangongo": ["Canacassala", "Gombe", "Zala"],
    "Pango Aluquém": ["Cazuangongo", "Pango Aluquém"],
    "Panguila": ["N_A"],
    "Piri": ["N_A"],
    "Quibaxe": ["Coxe", "Paredes", "Quibaxe"],
    "Quicunzo": ["N_A"],
    "Úcua": ["N_A"],
  },
  "Benguela": {
    "Babaera": ["N_A"],
    "Balombo": ["Balombo", "Maca Mombolo"],
    "Baía Farta": ["N_A"],
    "Benguela": ["N_A"],
    "Biópio": ["N_A"],
    "Bocoio": ["Bocoio", "Cubal do Lumbo", "Monte Belo"],
    "Bolonguera": ["N_A"],
    "Caimbambo": ["Caiave", "Caimbambo", "Viangombe"],
    "Canhamela": ["N_A"],
    "Capupa": ["N_A"],
    "Catengue": ["N_A"],
    "Catumbela": ["N_A"],
    "Chicuma": ["N_A"],
    "Chila": ["N_A"],
    "Chindumbo": ["N_A"],
    "Chongorói": ["Chongorói"],
    "Cubal": ["N_A"],
    "Dombe Grande": ["N_A"],
    "Egito Praia": ["Canjala", "Egito Praia"],
    "Ganda": ["N_A"],
    "Iambala": ["N_A"],
    "Lobito": ["N_A"],
    "Navegantes": ["N_A"],
  },
  "Bié": {
    "Andulo": ["Andulo", "Cassumbe", "Chivaúlo"],
    "Belo Horizonte": ["N_A"],
    "Calucinga": ["N_A"],
    "Camacupa": ["Camacupa", "Cuanza", "Muinha"],
    "Cambândua": ["N_A"],
    "Catabola": ["Caiuera", "Catabola", "Sande"],
    "Chicala": ["N_A"],
    "Chinguar": ["Cangote", "Chinguar", "Cutato"],
    "Chipeta": ["Chipeta", "Chiuca"],
    "Chitembo": ["Cachingues", "Chitembo", "Malengue"],
    "Cuemba": ["Cuemba", "Munhango", "Sachinemuna"],
    "Cuito": ["Cuito", "Cunje"],
    "Cunhinga": ["N_A"],
    "Luando": ["N_A"],
    "Lúbia": ["Dando", "Lúbia"],
    "Mumbué": ["Mumbué", "Mutumbo", "Soma Cuanza"],
    "Nharêa": ["Gamba", "Nharêa"],
    "Ringoma": ["N_A"],
    "Umpulo": ["N_A"],
  },
  "Cabinda": {
    "Belize": ["Belize", "Luali"],
    "Buco Zau": ["N_A"],
    "Cabinda": ["N_A"],
    "Cacongo": ["Dinge", "Lândana"],
    "Liambo": ["N_A"],
    "Massabi": ["N_A"],
    "Miconje": ["N_A"],
    "Necuto": ["Inhuca", "Necuto"],
    "Ngoio": ["N_A"],
    "Tando Zinze": ["Malembo", "Tando Zinze"],
  },
  "Cuando": {
    "Cuito Cuanavale": ["Cuito Cuanavale", "Lupire"],
    "Dima": ["Cunjamba", "Cutuile"],
    "Dirico": ["Dirico", "Xamavera"],
    "Luengue": ["N_A"],
    "Luiana": ["N_A"],
    "Mavinga": ["N_A"],
    "Mucusso": ["N_A"],
    "Rivungo": ["N_A"],
    "Xipundo": ["N_A"],
  },
  "Cuanza Norte": {
    "Aldeia Nova": ["N_A"],
    "Ambaca": ["Bindo", "Camabatela", "Máua"],
    "Banga": ["Banga", "Cariamba"],
    "Bolongongo": ["N_A"],
    "Caculo Cabaça": ["N_A"],
    "Cambambe": ["Dange-ya-Menha", "Dondo", "São Pedro da Quilemba"],
    "Cazengo": ["Caculo Camuiza", "Ndalatando"],
    "Cêrca": ["N_A"],
    "Golungo Alto": ["Cambondo", "Golungo Alto", "Quilomboquía Puto"],
    "Lucala": ["Lucala", "Quiangombe"],
    "Luinga": ["N_A"],
    "Massangano": ["Massangano", "Zenza do Itombe"],
    "Ngonguembo": ["Camame", "Cavunga", "Quilombo dos Dembos"],
    "Quiculungo": ["N_A"],
    "Samba Cajú": ["Samba Cajú", "Samba Lucala"],
    "Tango": ["N_A"],
    "Terreiro": ["Quiquiemba", "Terreiro"],
  },
  "Cuanza Sul": {
    "Amboiva": ["N_A"],
    "Boa Entrada": ["N_A"],
    "Calulo": ["Cabuta", "Calulo"],
    "Cassongue": ["Atóme", "Cassongue", "Dumbi"],
    "Conda": ["Conda", "Cunjo"],
    "Condé": ["N_A"],
    "Ebo": ["Cassanje", "Ebo"],
    "Gabela": ["Assango", "Gabela"],
    "Gangula": ["N_A"],
    "Gungo": ["N_A"],
    "Lonhe": ["Cariango", "Lonhe"],
    "Munenga": ["N_A"],
    "Mussende": ["Mussende", "Quipaxi"],
    "Pambangala": ["N_A"],
    "Porto Amboím": ["Capolo", "Porto Amboím"],
    "Quenha": ["N_A"],
    "Quibala": ["Dala Cachibo", "Quibala"],
    "Quilenda": ["N_A"],
    "Quirimbo": ["N_A"],
    "Quissongo": ["N_A"],
    "Sanga": ["N_A"],
    "Seles": ["Botera", "Seles"],
    "Sumbe": ["Quicombo", "Sumbe"],
    "Waku Kungo": ["N_A"],
  },
  "Cubango": {
    "Caiundo": ["Caiundo", "Jamba Cueio"],
    "Calai": ["N_A"],
    "Chinguanja": ["N_A"],
    "Cuangar": ["N_A"],
    "Cuchi": ["N_A"],
    "Cutato": ["Vissati"],
    "Longa": ["Baixo Longa", "Longa"],
    "Mavengue": ["Maué", "Mavengue"],
    "Menongue": ["N_A"],
    "Nancova": ["Nancova", "Rito"],
    "Savate": ["Bondo Caíla", "Savate"],
  },
  "Cunene": {
    "Cafima": ["N_A"],
    "Cahama": ["Cahama", "Otchinjau"],
    "Chissuata": ["N_A"],
    "Chitado": ["N_A"],
    "Chiéde": ["N_A"],
    "Cuanhama": ["Môngua", "Ondjiva"],
    "Curoca": ["N_A"],
    "Cuvelai": ["N_A"],
    "Humbe": ["Humbe", "Mucope"],
    "Mupa": ["N_A"],
    "Namacunde": ["N_A"],
    "Naulila": ["N_A"],
    "Nehone": ["Evale", "Nehone"],
    "Ombadja": ["Ombala-yo-Mungu", "Xangongo"],
  },
  "Huambo": {
    "Alto Hama": ["N_A"],
    "Bailundo": ["Bailundo", "Lunge", "Luvemba"],
    "Bimbe": ["Bimbe", "Hengue"],
    "Cachiungo": ["Cachiungo", "Chinhama"],
    "Caála": ["N_A"],
    "Chicala Choloanga": ["Chicala", "Mbave"],
    "Chilata": ["N_A"],
    "Chinjenje": ["Chiaca", "Chinjenje"],
    "Cuima": ["Catata", "Cuima"],
    "Ecunha": ["Ecunha", "Quipeio"],
    "Galanga": ["Cumbira", "Galanga"],
    "Huambo": ["Calima", "Huambo"],
    "Londuimbali": ["Londuimbali", "Ussoque"],
    "Longonjo": ["Longonjo", "Lépi"],
    "Mungo": ["Cambuengo", "Mungo"],
    "Sambo": ["Sambo", "Samboto"],
    "Ucuma": ["Cacoma", "Mundundo", "Ucuma"],
  },
  "Huíla": {
    "Caconda": ["Caconda", "Cusse", "Gungue", "Uaba"],
    "Cacula": ["Cacula", "Tchicuaqueia"],
    "Caluquembe": ["Calepi", "Caluquembe", "Negola"],
    "Capelongo": ["Capelongo", "Mulondo"],
    "Capunda Cavilongo": ["Capunda Cavilongo", "Quihita"],
    "Chibia": ["Chibia", "Jau"],
    "Chicomba": ["Chicomba", "Cutenda"],
    "Chicungo": ["N_A"],
    "Chipindo": ["Bambi", "Chipindo"],
    "Chituto": ["N_A"],
    "Cuvango": ["N_A"],
    "Dongo": ["N_A"],
    "Galangue": ["N_A"],
    "Gambos": ["Chiange", "Chimbemba"],
    "Hoque": ["N_A"],
    "Humpata": ["N_A"],
    "Jamba Mineira": ["Cassinga", "Jamba Mineira"],
    "Lubango": ["Huíla", "Lubango"],
    "Matala": ["N_A"],
    "Palanca": ["N_A"],
    "Quilengues": ["Dinde", "Impulo", "Quilengues"],
    "Quipungo": ["N_A"],
    "Viti Vivali": ["N_A"],
  },
  "Icolo e Bengo": {
    "Bom Jesus": ["N_A"],
    "Cabiri": ["N_A"],
    "Cabo Ledo": ["N_A"],
    "Calumbo": ["N_A"],
    "Catete": ["Caculo Cahango", "Cassoneca", "Catete", "Caxicane"],
    "Quiçama": ["Demba Chio", "Mumbondo", "Muxima", "Quixinge"],
    "Sequele": ["Funda", "Quifangondo", "Sequele"],
  },
  "Luanda": {
    "Belas": ["Barra do Cuanza", "Cabolombo", "Ramiros"],
    "Cacuaco": ["Cacuaco", "Kikolo"],
    "Camama": ["N_A"],
    "Cazenga": ["Cazenga", "Kima Kieza"],
    "Hoji-ya-Henda": ["N_A"],
    "Ingombota": ["N_A"],
    "Kilamba": ["Kilamba", "VilaFlôr"],
    "Kilamba Kiaxi": ["Golfe", "Nova Vida"],
    "Maianga": ["N_A"],
    "Mulenvos": ["N_A"],
    "Mussulo": ["N_A"],
    "Rangel": ["N_A"],
    "Samba": ["N_A"],
    "Sambizanga": ["N_A"],
    "Talatona": ["Benfica", "Talatona"],
    "Viana": ["N_A"],
  },
  "Lunda Norte": {
    "Cafunfo": ["N_A"],
    "Camaxilo": ["N_A"],
    "Cambulo": ["Cachimo", "Nzage"],
    "Canzar": ["Canzar", "Luia"],
    "Capenda Camulemba": ["Capenda Camulemba", "Xinge"],
    "Cassanje Calucala": ["Cassanje Calucala", "Iongo"],
    "Caungula": ["N_A"],
    "Chitato": ["N_A"],
    "Cuango": ["N_A"],
    "Cuilo": ["Caluango", "Cuilo"],
    "Dundo": ["Dundo", "Luachimo"],
    "Luangue": ["N_A"],
    "Lubalo": ["Lubalo", "Muvuluege"],
    "Lucapa": ["Camissombo", "Lucapa"],
    "Luremo": ["N_A"],
    "Lóvua": ["N_A"],
    "Mussungue": ["Caíta", "Mussungue"],
    "Xa-Cassau": ["Capaia", "Xa Cassau"],
    "Xá Muteba": [],
  },
  "Lunda Sul": {
    "Alto Chicapa": ["N_A"],
    "Cacolo": ["N_A"],
    "Cassai-Sul": ["N_A"],
    "Cassengo": ["N_A"],
    "Cazage": ["N_A"],
    "Chiluage": ["N_A"],
    "Dala": ["N_A"],
    "Luma Cassai": ["N_A"],
    "Muangueji": ["N_A"],
    "Muconda": ["N_A"],
    "Muriege": ["N_A"],
    "Saurimo": ["Mona Quimbundo", "Saurimo"],
    "Sombo": ["N_A"],
    "Xassengue": ["Cucumbi", "Xassengue"],
  },
  "Malanje": {
    "Caculama": ["Caculama", "Caxinga"],
    "Cacuso": ["Cacuso", "Soqueco"],
    "Cahombo": ["Cahombo", "Micanda"],
    "Calandula": ["Calandula", "Cota"],
    "Cambo Suinginge": ["N_A"],
    "Cambundi Catembo": ["Cambundi Catembo", "Dumba Cambango"],
    "Cangandala": ["Cangandala", "Caribo", "Culamagia"],
    "Capunda": ["Capunda", "Cunga Palanga", "Quimbango"],
    "Cateco Cangola": ["N_A"],
    "Cuale": ["N_A"],
    "Kiwaba Nzoji": ["Kiwaba Nzoji", "Mufuma"],
    "Kunda-dya-Baze": ["Kunda-dya-Baze", "Lemba"],
    "Luquembo": ["Dombo wa Zanga", "Luquembo"],
    "Malanje": ["Lombe", "Malanje"],
    "Marimba": ["Mangando", "Marimba"],
    "Massango": ["N_A"],
    "Mbanjiya Ngola": ["Cabombo", "Mbanjiya Ngola"],
    "Milando": ["N_A"],
    "Muquixe": ["N_A"],
    "Ngola Luiji": ["Cambaxe", "Ngola Luiji"],
    "Pungu a Ndongo": ["N_A"],
    "Quela": ["Bângalas", "Quela"],
    "Quihuhu": ["Quihuhu", "Quinguengue"],
    "Quirima": ["Quirima", "Sautar"],
    "Quitapa": ["N_A"],
    "Quêssua": ["N_A"],
    "Xandel": ["Moma", "Xandel"],
  },
  "Moxico": {
    "Alto Cuito": ["N_A"],
    "Camanongue": ["N_A"],
    "Cangamba": ["Cangamba", "Cangombe", "Cassamba", "Muié"],
    "Cangumbe": ["N_A"],
    "Chiúme": ["N_A"],
    "Lucusse": ["N_A"],
    "Luena": ["Cassongo", "Luena"],
    "Lumbala Nguimbo": ["Lumbala Nguimbo", "Mussuma Mitete", "Sessa"],
    "Lutembo": ["Lutembo", "Luvuei"],
    "Lutuai": ["N_A"],
    "Léua": ["Liangongo", "Léua"],
    "Ninda": ["N_A"],
  },
  "Moxico Leste": {
    "Caianda": ["N_A"],
    "Cameia": ["N_A"],
    "Cazombo": ["Cazombo", "Lumbala Caquembe"],
    "Lago Dilolo": ["N_A"],
    "Luacano": ["N_A"],
    "Luau": ["N_A"],
    "Lóvua do Zambeze": ["N_A"],
    "Macondo": ["Calunda", "Macondo"],
    "Nana Candundo": ["N_A"],
  },
  "Namibe": {
    "Bibala": ["Bibala", "Caitou", "Capangombe", "Lola"],
    "Cacimbas": ["N_A"],
    "Camucuio": ["Camucuio", "Chingo", "Mamué"],
    "Iona": ["N_A"],
    "Lucira": ["Bentiaba", "Lucira"],
    "Moçâmedes": ["N_A"],
    "Sacomar": ["N_A"],
    "Tômbwa": ["N_A"],
    "Virei": ["Cainde", "Virei"],
  },
  "Uíge": {
    "Alto Zaza": ["Alto Zaza", "Cuango Calumbo"],
    "Ambuíla": [],
    "Bembe": ["Bembe", "Mabaia"],
    "Bungo": ["N_A"],
    "Cangola": ["Bengo", "Caiongo", "Cangola"],
    "Damba": ["Camatambo", "Damba", "Lêmboa", "Petecusso"],
    "Lucunga": ["N_A"],
    "Maquela do Zombo": ["Maquela do Zombo", "Quibocolo"],
    "Massau": ["Macolo", "Massau"],
    "Milunga": ["Macocola", "Milunga"],
    "Mucaba": ["Mucaba", "Uando Mucaba"],
    "Negage": ["Dimuca", "Negage", "Quisseque"],
    "Nova Esperança": ["Cuilo Camboso"],
    "Nsosso": ["N_A"],
    "Puri": ["N_A"],
    "Quimbele": ["Icoca", "Quimbele"],
    "Quipedro": ["N_A"],
    "Sacandica": ["Béu", "Cuilo Futa", "Sacandica"],
    "Sanza Pombo": ["Alfândega", "Cuilo Pombo", "Sanza Pombo", "Uamba"],
    "Songo": ["Quivuenga", "Songo"],
    "Uíge": ["Luanga", "Uíge"],
    "Vista Alegre": ["Cambamba", "Vista Alegre"],
  },
  "Zaire": {
    "Cuimba": ["Buela", "Cuimba", "Luvaca"],
    "Lufico": ["Lufico", "Mpala"],
    "Luvo": ["N_A"],
    "Mbanza Kongo": ["Caluca", "Madimba", "Mbanza Kongo", "Quiende"],
    "Nzeto": ["Musserra", "Nzeto"],
    "Nóqui": ["N_A"],
    "Quindeje": ["Quibala-Norte", "Quindeje"],
    "Quêlo": ["N_A"],
    "Serra de Canda": ["N_A"],
    "Soyo": ["Pedra de Feitiço", "Soyo"],
    "Tomboco": ["Quinsimba", "Quinzau", "Tomboco"],
  },
};

export const MUNICIPIOS_POR_PROVINCIA: Record<ProvinciaAngola, string[]> =
  Object.fromEntries(
    PROVINCIAS_ANGOLA.map((p) => [p, Object.keys(DPA_ANGOLA[p]).sort((a, b) => a.localeCompare(b, "pt"))]),
  ) as Record<ProvinciaAngola, string[]>;

export function getMunicipios(provincia: ProvinciaAngola | undefined | null | ""): string[] {
  if (!provincia) return [];
  return MUNICIPIOS_POR_PROVINCIA[provincia as ProvinciaAngola] ?? [];
}

export function getComunas(
  provincia: ProvinciaAngola | undefined | null | "",
  municipio: string | undefined | null | "",
): string[] {
  if (!provincia || !municipio) return [];
  return DPA_ANGOLA[provincia as ProvinciaAngola]?.[municipio] ?? [];
}

export function isMunicipioValido(provincia: ProvinciaAngola, municipio: string): boolean {
  return getMunicipios(provincia).includes(municipio);
}

export function isComunaValida(
  provincia: ProvinciaAngola,
  municipio: string,
  comuna: string,
): boolean {
  return getComunas(provincia, municipio).includes(comuna);
}
